apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: default/sample-springboot-dekorate-istio
      jib:
        args:
          - -DskipTests
  tagPolicy:
    customTemplate:
      template: "1.0"
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/*.yml
    - k8s/*.yaml