apiVersion: skaffold/v4beta5
kind: Config
build:
  artifacts:
    - image: piomin/sample-springboot-dekorate-istio
      jib:
        args:
          - -DskipTests
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/*.json
    - k8s/*.yaml